---
- name: Install Graylog on localhost
  hosts: localhost
  become: yes
  vars:
    graylog_version: "4.2"
    graylog_password_secret: "somepasswordpepper"
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_web_endpoint_uri: "http://{{ ansible_default_ipv4.address }}:9000/api"
    graylog_elasticsearch_hosts: "http://{{ ansible_default_ipv4.address }}:9200"
    graylog_mongodb_uri: "mongodb://127.0.0.1:27017/graylog"
    graylog_http_bind_address: "0.0.0.0"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install apt-transport-https and gnupg
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install pymongo
      pip:
        name: pymongo
        state: present

    - name: Add Elasticsearch APT key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Configure Elasticsearch cluster name
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?cluster.name'
        line: 'cluster.name: graylog'
        state: present

    - name: Configure Elasticsearch node name
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?node.name'
        line: 'node.name: node-1'
        state: present

    - name: Configure Elasticsearch network host
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host'
        line: 'network.host: 0.0.0.0'
        state: present

    - name: Configure Elasticsearch HTTP port
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port'
        line: 'http.port: 9200'
        state: present

    - name: Configure Elasticsearch discovery type
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?discovery.type'
        line: 'discovery.type: single-node'
        state: present

    - name: Ensure Elasticsearch is started and enabled
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Add MongoDB APT key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present

    - name: Add MongoDB repository for Debian 11
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main"
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Ensure MongoDB is started and enabled
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Add Graylog repository key
      apt_key:
        url: "https://packages.graylog2.org/repo/debian/pubkey.gpg"
        state: present

    - name: Add Graylog repository
      apt_repository:
        repo: "deb https://packages.graylog2.org/repo/debian/ stable {{ graylog_version }}"
        state: present

    - name: Install Graylog
      apt:
        name: graylog-server
        state: present

    - name: Create journal directory
      file:
        path: /data/journal
        state: directory
        owner: graylog
        group: graylog
        mode: '0755'


    - name: Configure Graylog server
      template:
        src: templates/graylog.conf.j2
        dest: /etc/graylog/server/server.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Graylog

    - name: Ensure Graylog is started and enabled
      service:
        name: graylog-server
        state: started
        enabled: yes

  handlers:
    - name: Restart Graylog
      service:
        name: graylog-server
        state: restarted
